export const MENTOR_SEED_DATA = [
  {
    id: "1", name: "Nguyễn Thị Linh", title: "Senior HR Manager", company: "Vingroup",
    field: "HR", experience: 8, rating: 4.9, reviews: 127, price: 350000,
    avatar: "https://images.unsplash.com/photo-1736939678218-bd648b5ef3bb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhc2lhbiUyMGJ1c2luZXNzJTIwd29tYW4lMjBIUiUyMG1hbmFnZXIlMjBzbWlsaW5nfGVufDF8fHx8MTc3MjEyODEyOXww&ixlib=rb-4.1.0&q=80&w=400",
    tags: ["HR", "Tuyển dụng", "Phỏng vấn hành vi"], available: true,
    bio: "8 năm kinh nghiệm HR tại các tập đoàn lớn. Chuyên gia phỏng vấn hành vi, đã phỏng vấn hơn 500 ứng viên.",
    specialties: ["Behavioral Interview", "HR Strategy", "Talent Acquisition"],
    companies: ["Vingroup", "FPT Corporation", "VNG"],
    sessionsDone: 248, responseTime: "< 2 giờ",
  },
  {
    id: "2", name: "Trần Minh Khoa", title: "Engineering Manager", company: "Shopee",
    field: "IT", experience: 6, rating: 4.8, reviews: 95, price: 450000,
    avatar: "https://images.unsplash.com/photo-1752118464988-2914fb27d0f0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhc2lhbiUyMG1hbiUyMHByb2Zlc3Npb25hbCUyMHRlY2glMjBpbnRlcnZpZXd8ZW58MXx8fHwxNzcyMTI4MTI2fDA&ixlib=rb-4.1.0&q=80&w=400",
    tags: ["IT", "Software Engineering", "System Design"], available: true,
    bio: "Engineering Manager tại Shopee với 6 năm kinh nghiệm trong ngành. Chuyên môn phỏng vấn technical cho các vị trí Software Engineer.",
    specialties: ["System Design", "Coding Interview", "Technical Leadership"],
    companies: ["Shopee", "Tiki", "Google (internship)"],
    sessionsDone: 183, responseTime: "< 3 giờ",
  },
  {
    id: "3", name: "Lê Hương Giang", title: "Marketing Director", company: "Unilever Vietnam",
    field: "Marketing", experience: 10, rating: 4.7, reviews: 68, price: 400000,
    avatar: "https://images.unsplash.com/photo-1771240730126-594a8ab66be1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3b21hbiUyMG1hcmtldGluZyUyMHByb2Zlc3Npb25hbCUyMHBvcnRyYWl0JTIwb2ZmaWNlfGVufDF8fHx8MTc3MjEyODEzMHww&ixlib=rb-4.1.0&q=80&w=400",
    tags: ["Marketing", "Brand Strategy", "Digital Marketing"], available: false,
    bio: "10 năm kinh nghiệm marketing tại các tập đoàn FMCG. Chuyên gia phỏng vấn các vị trí marketing từ junior đến senior.",
    specialties: ["Brand Management", "Digital Marketing", "Case Interview"],
    companies: ["Unilever", "P&G", "L'Oréal"],
    sessionsDone: 156, responseTime: "< 4 giờ",
  },
  {
    id: "4", name: "Phạm Đức Anh", title: "Investment Manager", company: "KPMG",
    field: "Finance", experience: 7, rating: 4.6, reviews: 52, price: 500000,
    avatar: "https://images.unsplash.com/photo-1770363760820-b871452de45f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx5b3VuZyUyMGFzaWFuJTIwcHJvZmVzc2lvbmFsJTIwbWFuJTIwc3VpdCUyMGNvbmZpZGVudHxlbnwxfHx8fDE3NzIxMjgxMjl8MA&ixlib=rb-4.1.0&q=80&w=400",
    tags: ["Finance", "Investment Banking", "Consulting"], available: true,
    bio: "7 năm kinh nghiệm tại Big4, chuyên gia phỏng vấn case study và technical finance cho các vị trí finance, consulting.",
    specialties: ["Financial Modeling", "Case Interview", "Consulting"],
    companies: ["KPMG", "McKinsey", "Deloitte"],
    sessionsDone: 134, responseTime: "< 2 giờ",
  },
  {
    id: "5", name: "Vũ Thị Thanh", title: "Product Manager", company: "VNG Corporation",
    field: "Product", experience: 5, rating: 4.8, reviews: 41, price: 380000,
    avatar: "https://images.unsplash.com/photo-1770364020204-102331b625ea?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwcm9mZXNzaW9uYWwlMjBhc2lhbiUyMHdvbWFuJTIwYnVzaW5lc3MlMjBtZW50b3J8ZW58MXx8fHwxNzcyMTI4MTI2fDA&ixlib=rb-4.1.0&q=80&w=400",
    tags: ["Product", "UX", "Agile"], available: true,
    bio: "5 năm kinh nghiệm Product Manager tại VNG. Chuyên gia phỏng vấn product sense, metric analysis và case study.",
    specialties: ["Product Sense", "Metric Analysis", "Product Strategy"],
    companies: ["VNG", "Zalo", "Grab"],
    sessionsDone: 97, responseTime: "< 1 giờ",
  },
  {
    id: "6", name: "Đặng Hoàng Nam", title: "Data Science Lead", company: "MoMo",
    field: "IT", experience: 6, rating: 4.7, reviews: 38, price: 420000,
    avatar: "https://images.unsplash.com/photo-1752118464988-2914fb27d0f0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhc2lhbiUyMG1hbiUyMHByb2Zlc3Npb25hbCUyMHRlY2glMjBpbnRlcnZpZXd8ZW58MXx8fHwxNzcyMTI4MTI2fDA&ixlib=rb-4.1.0&q=80&w=400",
    tags: ["Data Science", "ML", "Analytics"], available: true,
    bio: "6 năm kinh nghiệm trong lĩnh vực Data Science và Machine Learning. Chuyên phỏng vấn cho các vị trí Data Analyst, Data Scientist.",
    specialties: ["Machine Learning", "Statistical Analysis", "SQL & Python"],
    companies: ["MoMo", "VNPay", "FPT AI"],
    sessionsDone: 112, responseTime: "< 3 giờ",
  },
];
